sudo: required

language: node_js
node_js:
  - "7"

services:
  - docker

before_install:
  - docker build -t nischayv/jotunheimr .
  - docker ps -a

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push nischayv/jotunheimr;
    fi